// <auto-generated />
namespace PhamThangWAD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_soluong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_soluong));
        
        string IMigrationMetadata.Id
        {
            get { return "202112150455440_add_soluong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
