// <auto-generated />
namespace PhamThangWAD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202112160432592_update_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
